CC = gcc
PROGS = problem2 problem4 problem6

all:
	$(PROGS)

problem2: problem2.c
	$(CC) problem2.c -o problem2
problem4: problem4.c
	$(CC) problem4.c -o problem4
problem5: problem6.c
	$(CC) problem6.c -o problem6

clean:
	rm *.o problem2 problem4 problem6

